"""Initial

Revision ID: 7c59730f0706
Revises: 
Create Date: 2021-03-14 02:20:48.403275

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7c59730f0706'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrolle',
                    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
                    sa.Column('surname', mysql.VARCHAR(length=30), nullable=True),
                    sa.Column('name', mysql.VARCHAR(length=20), nullable=True),
                    sa.Column('middle_name', mysql.VARCHAR(length=20), nullable=True),
                    sa.Column('gender', mysql.VARCHAR(length=1), nullable=True),
                    sa.Column('nationality', mysql.VARCHAR(length=30), nullable=True),
                    sa.Column('birthdate', sa.DATE(), nullable=True),
                    sa.Column('home_address', mysql.VARCHAR(length=256), nullable=True),
                    sa.Column('CT_rating', mysql.SMALLINT(unsigned=True), autoincrement=False, nullable=True),
                    sa.Column('passing_score', mysql.SMALLINT(unsigned=True), autoincrement=False, nullable=True),
                    sa.Column('university_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['university_id'], ['university.id'], name='enrolle_ibfk_1'),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_collate='utf8mb4_0900_ai_ci',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )
    op.create_table('university',
                    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
                    sa.Column('university_name', mysql.VARCHAR(length=80), nullable=True),
                    sa.Column('university_description', mysql.VARCHAR(length=200), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_collate='utf8mb4_0900_ai_ci',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('university')
    op.drop_table('enrolle')
    # ### end Alembic commands ###
